-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "count_history" (
    "uid" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "count" INT4 NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "count_history_pkey" PRIMARY KEY ("uid")
);

