CREATE TABLE "count_history" (
	"uid" int4 PRIMARY KEY GENERATED ALWAYS AS IDENTITY (INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"count" int4 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
