/* Regenerates the initial Prisma migration every SQL Prisma project ships
   with (src/templates/db/migrations/prisma-<provider>-<table>/). Each one is
   the real `prisma migrate diff --from-empty` output for the schema
   generatePrismaSchema emits, so a fresh project's `db:migrate` creates the
   example table and the migrated database matches the schema exactly.
   Run after changing the schema generator or bumping prisma:
   `bun scripts/generate-prisma-migrations.ts`. The scratch schemas live in
   the OS temp directory, never in the repository or the caller's cwd. */
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { generatePrismaSchema } from '../src/generators/prisma/generatePrismaSchema';
import {
	getMigrationLockProvider,
	getPrismaMigrationTemplateName,
	getPrismaTarget,
	initialPrismaMigrationName
} from '../src/generators/prisma/prismaTargets';
import type { AvailablePrismaDialect } from '../src/types';

const repository = resolve(import.meta.dir, '..');
const templates = join(repository, 'src/templates/db/migrations');
const prisma = join(repository, 'node_modules/.bin/prisma');

/* One engine per SQL provider: mariadb shares mysql's output, and every host
   variant of an engine shares its provider's DDL. */
/* `migrate diff` never connects for --from-empty/--to-schema, but without a
   config datasource Prisma 7.10 intermittently prints an empty diff. These
   URLs only have to be well-formed for the provider. */
const unusedUrls: Record<string, string> = {
	cockroachdb: 'postgresql://unused@localhost:1/unused',
	mysql: 'mysql://unused@localhost:1/unused',
	postgresql: 'postgresql://unused@localhost:1/unused',
	sqlite: 'file:./unused.db',
	sqlserver: 'sqlserver://localhost:1;database=unused'
};

const engines: AvailablePrismaDialect[] = [
	'cockroachdb',
	'mssql',
	'mysql',
	'postgresql',
	'sqlite'
];

export const renderInitialMigration = (
	databaseEngine: AvailablePrismaDialect,
	usesAuth: boolean
) => {
	const target = getPrismaTarget(databaseEngine, 'none');
	const scratch = mkdtempSync(join(tmpdir(), 'prisma-migration-'));
	try {
		const schema = join(scratch, 'schema.prisma');
		writeFileSync(
			schema,
			generatePrismaSchema({
				authOption: usesAuth ? 'abs' : 'none',
				databaseDirectory: 'db',
				target
			})
		);
		writeFileSync(
			join(scratch, 'prisma.config.ts'),
			`export default { datasource: { url: '${unusedUrls[target.provider]}' }, schema: 'schema.prisma' };\n`
		);
		const diff = Bun.spawnSync(
			[
				prisma,
				'migrate',
				'diff',
				'--from-empty',
				'--to-schema',
				schema,
				'--script'
			],
			{ cwd: scratch, stderr: 'pipe', stdout: 'pipe' }
		);
		if (
			diff.exitCode !== 0 ||
			!diff.stdout.toString().includes('CREATE TABLE')
		)
			throw new Error(
				`prisma migrate diff failed for ${databaseEngine}: ${diff.stderr.toString()}`
			);

		return {
			lock: `# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "${getMigrationLockProvider(target.provider)}"\n`,
			name: getPrismaMigrationTemplateName(target.provider, usesAuth),
			sql: diff.stdout.toString()
		};
	} finally {
		rmSync(scratch, { force: true, recursive: true });
	}
};

export const prismaMigrationEngines = engines;

if (import.meta.main) {
	for (const databaseEngine of engines) {
		for (const usesAuth of [false, true]) {
			const { lock, name, sql } = renderInitialMigration(
				databaseEngine,
				usesAuth
			);
			const directory = join(templates, name);
			rmSync(directory, { force: true, recursive: true });
			mkdirSync(join(directory, initialPrismaMigrationName), {
				recursive: true
			});
			writeFileSync(
				join(directory, initialPrismaMigrationName, 'migration.sql'),
				sql
			);
			writeFileSync(join(directory, 'migration_lock.toml'), lock);
			console.log(`wrote ${name}`);
		}
	}
}
