import { prismaMongoDBVersion, versions } from '../../versions';
import type { PrismaTarget } from './prismaTargets';

type PrismaPackageJson = {
	dependencies: Record<string, string>;
	devDependencies: Record<string, string>;
	scripts: Record<string, string>;
};

const migrationScripts = (
	{ migration }: PrismaTarget,
	databaseDirectory: string
): Record<string, string> => {
	/* The Prisma MongoDB container is an unauthenticated single-node replica
	   set (see prismaMongoDBCompose), so its shell needs no credentials. */
	if (migration === 'push')
		return {
			'db:migrate': 'prisma db push',
			'db:mongodb': `docker compose -p mongodb -f ${databaseDirectory}/docker-compose.db.yml exec -it db mongosh database`
		};
	if (migration === 'libsql')
		return {
			'db:migrate': `bun ${databaseDirectory}/migrate.ts`,
			'db:migrate:dev': 'prisma migrate dev'
		};

	return {
		'db:migrate': 'prisma migrate deploy',
		'db:migrate:dev': 'prisma migrate dev'
	};
};

/* Dependencies and scripts a Prisma project adds. Versions are always the
   pinned ones — never `--lts` resolved — because npm's `latest` dist-tag for
   `prisma` currently points at a release candidate.

   The client is generated by the project's own `postinstall` (a root package
   script, which package managers always run) and by `db:generate`; it never
   depends on a dependency's lifecycle script being trusted. */
export const getPrismaPackageJson = (
	target: PrismaTarget,
	databaseDirectory: string
): PrismaPackageJson => {
	const version =
		target.line === 'prisma6' ? prismaMongoDBVersion : versions.prisma;
	const dependencies: Record<string, string> = {
		'@prisma/client': version
	};
	if (target.adapter) dependencies[target.adapter.packageName] = version;
	if (target.migration === 'libsql')
		dependencies['@libsql/client'] = versions['@libsql/client'];

	return {
		dependencies,
		devDependencies: { prisma: version },
		scripts: {
			'db:generate': 'prisma generate',
			'db:studio': 'prisma studio',
			postinstall: 'prisma generate',
			...migrationScripts(target, databaseDirectory)
		}
	};
};
